### ISSUE TITLE
JSON config isnt syntactically correct, and has duplicate fields

### ISSUE THREAD

**Issue by csabo** [chrisbraddock/node-cgmon#1]
the json config file isn't valid, I resolved the issue by encapsulating the keys in quotes.

You also have duplicate key:value pairs in the config.

**Comment by chrisbraddock** [comment]
Not running against the sample json, I haven't experienced this issue.

I'd been copy/pasting the [JavaScript object literal out of cgmon.js](https://github.com/chrisbraddock/node-cgmon/blob/master/cgmon.js#L50) in an attempt to keep the sample file up to date as config options were added during coding. I'll change my strategy there.

The duplicate config values are another oversight.

I'll address both issues the next opportunity I get to put some time in to this - likely the week after next.

If you find any other issues, it'd be cool if you submitted a pull request.

Also I appreciate the edits to your issue.

**Comment by csabo** [comment]
I will do that in the future. my apologies on the unedited. I was having a
bad day.

Sent from my iPhone

On Jan 24, 2014, at 8:53 PM, Chris Braddock notifications@github.com
wrote:

Not running against the sample json, I haven't experienced this issue.

I'd been copy/pasting the JavaScript object literal out of
cgmon.jshttps://github.com/chrisbraddock/node-cgmon/blob/master/cgmon.js#L50in
an attempt to keep the sample file up to date as config options were
added during coding. I'll change my strategy there.

The duplicate config values are another oversight.

I'll address both issues the next opportunity I get to put some time in to
this - likely the week after next.

If you find any other issues, it'd be cool if you submitted a pull request.

Also I appreciate the edits to your issue.

—
Reply to this email directly or view it on
GitHubhttps://github.com/chrisbraddock/node-cgmon/issues/1#issuecomment-33277967
.

**Comment by chrisbraddock** [comment]
It happens to us all. :) Hope you're feeling better.

**Comment by csabo** [comment]
Would it be of assistance if I provided the fixed sample config, or are you
already taking care of it?

-Chris

On Fri, Jan 24, 2014 at 9:00 PM, Chris Braddock notifications@github.comwrote:

> It happens to us all. :) Hope you're feeling better.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chrisbraddock/node-cgmon/issues/1#issuecomment-33278167
> .

## 

“_Never commit to memory what can be easily looked up in books”_ -
Albert Einstein.

**Comment by chrisbraddock** [comment]
I guess I can fix the JSON at least. I was going to wrap it in to some other changes I want to make but I can separate that out. Few minutes...

**Comment by csabo** [comment]
Done :) here ya go, your sample with keys properly encased, and the
duplicates removed.

{
    "minerName": "my miner",
    "cgminer": {
        "startWaitSeconds": 5,
        "cmd": "./start_screen.sh",
        "args": [],
        "host": "127.0.0.1",
        "port": "4028"
    },
    "minMHSAv": 1,
    "minMHS5s": 1,
    "numGPUs": 1,
    "maxTemp": 85,
    "maxFanSpeed": 4500,
    "maxHErrPct": 0,
    "maxRejPct": 0,
    "maxGetCgminerPidAttempts": 5,
    "monitorIntervalSeconds": 5,
    "logLevel": "debug",
    "logEnabled": true,
    "logPath": "cgmon.log",
    "emailEnabled": false,
    "maxEmailIntervalMinutes": 60,
    "email": {
        "user": "youremail@gmail.com",
        "pass": "your gmail password",
        "from": "from email address",
        "to": "to email address",
        "subject": "cgmon",
        "template": "email-template.html"
    },
    "apiResponseThresholdSeconds": 10
}

On Fri, Jan 24, 2014 at 9:08 PM, Chris Braddock notifications@github.comwrote:

> I guess I can fix the JSON at least. I was going to wrap it in to some
> other changes I want to make. Few minutes...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chrisbraddock/node-cgmon/issues/1#issuecomment-33278413
> .

## 

“_Never commit to memory what can be easily looked up in books”_ -
Albert Einstein.

**Comment by chrisbraddock** [comment]
Ha sorry I missed your comment while I was doing the same and committing.
