### ISSUE TITLE
MHS should allow for value below 1

### ISSUE THREAD

**Issue by rootedsoftware** [chrisbraddock/node-cgmon#2]
Since this program can also be used to monitor litecoin and other scrypt based coins the value for MHS should allow a decimal value. Such as .8 or .85. 

Thanks

**Comment by chrisbraddock** [comment]
It should allow for decimal numbers. The code simply does a less than comparison. As of right now, it only sends an email if the hashing rate falls below the config value. Probably at some point I should allow restart/reboot instead.

If you're seeing some issue using a decimal value, post back.
