### ISSUE TITLE
fix code around _.defaults() regarding email

### ISSUE THREAD

**Issue by chrisbraddock** [chrisbraddock/node-cgmon#4]
fix code around _.defaults() so selective email values in config.json don't eliminate needed email values ...

**Comment by jadeye** [comment]
Hello,

Do your script work 'out-of-the-box' for gmail ro are there other components necessary for emails??

Thank you

**Comment by chrisbraddock** [comment]
It works out of the box. If you're having a specific problem you can let me know.

**Comment by jadeye** [comment]
Thanx for sharing your work.
